use_frameworks!

platform :watchos, '7.0'

target 'AppleWatchLogger_Example Watch App' do
  pod 'AppleWatchLogger', :path => '../'

  target 'AppleWatchLogger_Example Watch AppTests' do
    inherit! :search_paths

    
  end
end
